name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Run the pipeline on changes to the main branch

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.5.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest
            docker stop my-node-app || true
            docker rm my-node-app || true
            docker run -d --name my-node-app -p 80:3000 ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest
