name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # This triggers the workflow when you push to the 'main' branch

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # This checks out your code from the repo

      - name: Show Docker Username
        run: echo "Docker Username: ${{ secrets.DOCKER_USERNAME }}"  # Check if username is correctly pulled

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin  # Logs into Docker Hub

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest .  # Builds the Docker image
          docker push ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest  # Pushes the image to Docker Hub

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.5.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest  # Pulls the Docker image from Docker Hub
            docker stop my-node-app || true  # Stops any running container
            docker rm my-node-app || true  # Removes the stopped container
            docker run -d --name my-node-app -p 80:3000 ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest  # Runs the Docker container on your server
